all: atod NosICreate NosIVerify ascTo612
atod: atod.c
	cc -o atod atod.c
NosICreate: NosICreate.c	
	cc -o NosICreate NosICreate.c
NosIVerify: NosIVerify.c
	cc -o NosIVerify NosIVerify.c
ascTo612: ascTo612.c
	cc -o ascTo612 ascTo612.c
